name: CI

on: [push, pull_request]

jobs:
  build-wheels:
    # Run on external PRs, but not on internal PRs, to avoid duplicate runs
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    name: Build wheels on ${{ matrix.cibw-only }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-latest, cibw-only: cp311-manylinux_x86_64 }
          - { os: ubuntu-latest, cibw-only: cp312-manylinux_x86_64 }
          - { os: ubuntu-latest, cibw-only: cp313-manylinux_x86_64 }
          - { os: ubuntu-latest, cibw-only: cp314-manylinux_x86_64 }

          - { os: ubuntu-24.04-arm, cibw-only: cp311-manylinux_aarch64 }
          - { os: ubuntu-24.04-arm, cibw-only: cp312-manylinux_aarch64 }
          - { os: ubuntu-24.04-arm, cibw-only: cp313-manylinux_aarch64 }
          - { os: ubuntu-24.04-arm, cibw-only: cp314-manylinux_aarch64 }

          - { os: macos-15-intel, cibw-only: cp311-macosx_x86_64 }
          - { os: macos-15-intel, cibw-only: cp312-macosx_x86_64 }
          - { os: macos-15-intel, cibw-only: cp313-macosx_x86_64 }
          - { os: macos-15-intel, cibw-only: cp314-macosx_x86_64 }

          - { os: macos-latest, cibw-only: cp311-macosx_arm64 }
          - { os: macos-latest, cibw-only: cp312-macosx_arm64 }
          - { os: macos-latest, cibw-only: cp313-macosx_arm64 }
          - { os: macos-latest, cibw-only: cp314-macosx_arm64 }

          - { os: windows-latest, cibw-only: cp311-win_amd64 }
          - { os: windows-latest, cibw-only: cp312-win_amd64 }
          - { os: windows-latest, cibw-only: cp313-win_amd64 }
          - { os: windows-latest, cibw-only: cp314-win_amd64 }

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Use Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - uses: mamba-org/setup-micromamba@v2
        if: runner.os == 'macOS'
        with:
          micromamba-version: "latest"
          environment-name: richdem
          create-args: >-
            llvm-openmp
          cache-environment: true

      - name: Set OPENMP_PREFIX (macOS)
        if: runner.os == 'macOS'
        shell: bash -l {0}
        run: |
          echo "OPENMP_PREFIX=${CONDA_PREFIX}" >> "$GITHUB_ENV"

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3
        with:
          only: ${{ matrix.cibw-only }}

      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.cibw-only }}
          path: ./wheelhouse/*.whl
